#!/bin/sh
# NFR006-03: scans service logs for secrets. Used by CI (ci.yml `stack` job, on compose.log) and locally:
#   sh scripts/scan-logs.sh compose.log [.env]
#
# 1. gitleaks with the repository rules (.gitleaks.toml), in directory mode (no git). Each finding is printed
#    with its rule, line and service and the value redacted.
#    GITLEAKS=/absolute/path/to/gitleaks, else `gitleaks` in PATH or ./gitleaks. --no-gitleaks skips this step.
# 2. Canary: every secret value of the env file (default .env, generated by scripts/init-env.sh, so the
#    values are known) must not appear verbatim in the log. Only the variable NAME is ever printed.
# Exit 1 on any finding.
set -eu
ROOT=$(cd "$(dirname "$0")/.." && pwd)

RUN_GITLEAKS=1
if [ "${1:-}" = "--no-gitleaks" ]; then RUN_GITLEAKS=0; shift; fi
LOG=${1:?usage: scan-logs.sh [--no-gitleaks] LOGFILE [ENV_FILE]}
ENV_FILE=${2:-.env}
[ -f "$LOG" ] || { echo "scan-logs: $LOG not found" >&2; exit 2; }
[ -s "$LOG" ] || { echo "scan-logs: $LOG is empty: nothing was collected, refusing to report it clean" >&2; exit 2; }

status=0

if [ "$RUN_GITLEAKS" -eq 1 ]; then
  bin=${GITLEAKS:-}
  if [ -z "$bin" ]; then
    if command -v gitleaks > /dev/null 2>&1; then bin=gitleaks; elif [ -x ./gitleaks ]; then bin="$PWD/gitleaks"; fi
  fi
  [ -n "$bin" ] || { echo "scan-logs: gitleaks not found (set GITLEAKS or use --no-gitleaks)" >&2; exit 2; }
  echo "== gitleaks (.gitleaks.toml) on $LOG"
  report=$(mktemp)
  # --verbose with --redact prints each finding with its rule, entropy and line and the value replaced by REDACTED:
  # the job log alone tells a real leak from a false positive, without opening the uploaded log.
  if ! (cd "$ROOT" && "$bin" dir --config .gitleaks.toml --redact --verbose --no-banner --exit-code 1 \
    --report-format json --report-path "$report" "$(cd "$(dirname "$LOG")" && pwd)/$(basename "$LOG")"); then
    echo "scan-logs: gitleaks found secrets in $LOG"
    # `docker compose logs` starts every line with "<service>-<n> |": name the service that wrote each finding.
    sed -n 's/^ *"StartLine": \([0-9][0-9]*\),*$/\1/p' "$report" | while read -r n; do
      service=$(sed -n "${n}p" "$LOG" | sed -n 's/^\([^ |]*\) *|.*/\1/p')
      echo "  finding on line $n${service:+, written by $service}"
    done
    status=1
  fi
  rm -f "$report"
fi

if [ -f "$ENV_FILE" ]; then
  echo "== canary: values of $ENV_FILE in $LOG"
  checked=0
  # Secret-looking names; public identifiers (…PUBKEY…, …_ID, URLs) are not secrets.
  names=$(sed -n 's/^\([A-Z0-9_]*\)=.*/\1/p' "$ENV_FILE" | grep -E '(PASSWORD|SECRET|PRIVATE|NSEC|KEK|TOKENS?|_KEY)$' | grep -v 'PUBKEY' || true)
  for name in $names; do
    value=$(sed -n "s/^$name=//p" "$ENV_FILE" | tail -n 1)
    if [ -z "$value" ] || [ "$value" = CHANGE_ME ]; then continue; fi
    # token lists (token:principal,...) are checked token by token
    for item in $(printf '%s' "$value" | tr ',' ' '); do
      token=${item%%:*}
      [ ${#token} -ge 8 ] || continue
      checked=$((checked + 1))
      if grep -F -q -- "$token" "$LOG"; then
        echo "LEAK: the value of $name appears in $LOG ($(grep -F -c -- "$token" "$LOG") lines)"
        status=1
      fi
    done
  done
  echo "canary: $checked secret values checked"
else
  echo "scan-logs: $ENV_FILE not found: canary step skipped" >&2
fi

[ "$status" -eq 0 ] && echo "scan-logs: no secrets found in $LOG"
exit "$status"
