import type { SovereigntyConfig } from './types';

/** Reference configuration matrix (spec Appendix B). */
export const PRESETS = {
  convenience: {
    custody: 'local',
    network: 'direct',
    identity: 'linked',
    persistence: 'replicated',
    messaging: 'nip17',
    files: 'relay-plain',
    telemetry: 'minimal',
    notifications: 'push',
    cloudBackup: 'ciphertext-user-key',
    crashReports: 'opt-in',
    remotePreviews: true,
    deliveryReceipts: true,
    readReceipts: false,
    quorum: 1,
    stripFileMetadata: true,
  },
  'private-resilient': {
    custody: 'external',
    network: 'multi-relay',
    identity: 'pseudonymous',
    persistence: 'replicated',
    messaging: 'nip17',
    files: 'client-encrypted',
    telemetry: 'minimal',
    notifications: 'privacy-push',
    cloudBackup: 'ciphertext-user-key',
    crashReports: 'off',
    remotePreviews: false,
    deliveryReceipts: true,
    readReceipts: false,
    quorum: 2,
    stripFileMetadata: true,
  },
  institutional: {
    custody: 'managed',
    network: 'private-relay',
    identity: 'verified',
    persistence: 'replicated',
    messaging: 'marmot',
    files: 'client-encrypted',
    telemetry: 'standard',
    notifications: 'privacy-push',
    cloudBackup: 'operator-managed',
    crashReports: 'opt-in',
    remotePreviews: false,
    deliveryReceipts: true,
    readReceipts: false,
    quorum: 1,
    stripFileMetadata: true,
  },
  sovereign: {
    custody: 'offline',
    network: 'private-relay',
    identity: 'pseudonymous',
    persistence: 'device',
    messaging: 'nip17',
    files: 'client-encrypted',
    telemetry: 'none',
    notifications: 'none',
    cloudBackup: 'off',
    crashReports: 'manual-export',
    remotePreviews: false,
    deliveryReceipts: false,
    readReceipts: false,
    quorum: 1,
    stripFileMetadata: true,
  },
  'sovereign-tor': {
    custody: 'offline',
    network: 'tor-only',
    identity: 'pseudonymous',
    persistence: 'device',
    messaging: 'marmot',
    files: 'client-encrypted',
    telemetry: 'none',
    notifications: 'none',
    cloudBackup: 'off',
    crashReports: 'off',
    remotePreviews: false,
    deliveryReceipts: false,
    readReceipts: false,
    quorum: 1,
    stripFileMetadata: true,
  },
} as const satisfies Record<string, SovereigntyConfig>;

export type PresetName = keyof typeof PRESETS;

export function preset(name: PresetName): SovereigntyConfig {
  return { ...PRESETS[name] };
}
