// Browser entry point: no Node built-ins, so bundlers need no stubs.
import type { StorageBackend } from './backends';
import type { DeviceKeyring } from './vault';

export type { StorageBackend } from './backends';
export * from './store';
export * from './vault';
export { LocalStorageBackend } from './localstorage';

function request<T>(req: IDBRequest<T>): Promise<T> {
  return new Promise((resolve, reject) => {
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

const STORES = ['kv', 'keys'];

function openDb(name: string, stores: string[]): Promise<IDBDatabase> {
  const req = indexedDB.open(name, 1);
  req.onupgradeneeded = () => {
    for (const s of stores) if (!req.result.objectStoreNames.contains(s)) req.result.createObjectStore(s);
  };
  return request(req);
}

/** IndexedDB backend (FR001-04): values are the already-sealed bytes; keys are the HMAC'd entry names. */
export class IndexedDBBackend implements StorageBackend {
  private db?: Promise<IDBDatabase>;
  constructor(readonly dbName = 'acceso-nostr') {}

  private store(mode: IDBTransactionMode): Promise<IDBObjectStore> {
    this.db ??= openDb(this.dbName, STORES);
    return this.db.then((db) => db.transaction('kv', mode).objectStore('kv'));
  }

  /** Resolve once the write transaction is durable (complete), not merely when the request succeeds. */
  private async write(op: (s: IDBObjectStore) => void): Promise<void> {
    const s = await this.store('readwrite');
    const done = new Promise<void>((resolve, reject) => {
      s.transaction.oncomplete = () => resolve();
      s.transaction.onerror = () => reject(s.transaction.error);
      s.transaction.onabort = () => reject(s.transaction.error);
    });
    op(s);
    await done;
  }

  async get(key: string) {
    const v = await request((await this.store('readonly')).get(key));
    return v === undefined ? undefined : new Uint8Array(v as ArrayBuffer);
  }
  put(key: string, value: Uint8Array) {
    return this.write((s) => s.put(value.slice().buffer, key));
  }
  delete(key: string) {
    return this.write((s) => s.delete(key));
  }
  async keys(prefix: string) {
    const range = IDBKeyRange.bound(prefix, `${prefix}\uffff`);
    return (await request((await this.store('readonly')).getAllKeys(range))).map(String);
  }

  close(): void {
    void this.db?.then((db) => db.close());
    this.db = undefined;
  }

  /** Remove every record of this database (used by "olvidar este navegador"). */
  static async destroy(dbName = 'acceso-nostr'): Promise<void> {
    await request(indexedDB.deleteDatabase(dbName) as unknown as IDBRequest<unknown>);
  }
}

/**
 * Device keyring: a non-extractable AES-GCM key generated by WebCrypto and kept in IndexedDB. The page
 * can use it but never read it; anyone with access to this browser profile can still use it, which
 * is why only the convenience profile may choose it (ADR 0007).
 */
export class WebCryptoKeyring implements DeviceKeyring {
  private key?: Promise<CryptoKey>;
  constructor(private readonly dbName = 'acceso-nostr', private readonly id = 'device-key') {}

  private async load(): Promise<CryptoKey> {
    const db = await openDb(this.dbName, STORES);
    try {
      const existing = (await request(db.transaction('keys', 'readonly').objectStore('keys').get(this.id))) as CryptoKey | undefined;
      if (existing) return existing;
      const key = await crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt']);
      await request(db.transaction('keys', 'readwrite').objectStore('keys').put(key, this.id));
      return key;
    } finally {
      db.close();
    }
  }

  async wrap(pt: Uint8Array): Promise<Uint8Array> {
    this.key ??= this.load();
    const iv = crypto.getRandomValues(new Uint8Array(12));
    const ct = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, await this.key, pt.slice()));
    const out = new Uint8Array(12 + ct.length);
    out.set(iv);
    out.set(ct, 12);
    return out;
  }

  async unwrap(data: Uint8Array): Promise<Uint8Array> {
    this.key ??= this.load();
    return new Uint8Array(await crypto.subtle.decrypt({ name: 'AES-GCM', iv: data.slice(0, 12) }, await this.key, data.slice(12)));
  }

  /** Delete the device key; the vault it protected becomes unreadable. */
  async forget(): Promise<void> {
    const db = await openDb(this.dbName, STORES);
    try {
      await request(db.transaction('keys', 'readwrite').objectStore('keys').delete(this.id));
    } finally {
      db.close();
      this.key = undefined;
    }
  }
}
